--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Raphael716/CustomServerKnockback
build-by-default: true
branches:
- main
projects:
  CustomServerKnoback:
    path: CustomServerKnoback/
...
